name: Grappa
description: Scaling irregular applications on commodity clusters.
pygments: true
highlighter: pygments

base: ''

url: http://grappa.io/

permalink: /blog/:title.html

exclude: [README.md, Makefile]

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: About
    link: "#about"
  - title: Docs
    link: "http://uwsampa.github.io/grappa-doxygen/html"
  - title:
    link: http://github.com/uwsampa/grappa
    icon: /images/GitHub-Mark-32px.png
