var annotated =
[
    [ "google", "namespacegoogle.html", null ],
    [ "Grappa", "namespace_grappa.html", "namespace_grappa" ],
    [ "Aggregator", "class_aggregator.html", "class_aggregator" ],
    [ "AggregatorBuffer", "class_aggregator_buffer.html", "class_aggregator_buffer" ],
    [ "AggregatorGenericCallHeader", "struct_aggregator_generic_call_header.html", "struct_aggregator_generic_call_header" ],
    [ "AggregatorMetrics", "class_aggregator_metrics.html", "class_aggregator_metrics" ],
    [ "Allocator", "class_allocator.html", "class_allocator" ],
    [ "AllocatorChunk", "struct_allocator_chunk.html", "struct_allocator_chunk" ],
    [ "AllReducer", "class_all_reducer.html", "class_all_reducer" ],
    [ "block_offset_t", "structblock__offset__t.html", "structblock__offset__t" ],
    [ "BufferVector", "class_buffer_vector.html", "class_buffer_vector" ],
    [ "CacheAllocator", "class_cache_allocator.html", "class_cache_allocator" ],
    [ "Cacheline", "struct_cacheline.html", "struct_cacheline" ],
    [ "CacheMetrics", "class_cache_metrics.html", null ],
    [ "CacheRO", "class_cache_r_o.html", "class_cache_r_o" ],
    [ "CacheRW", "class_cache_r_w.html", "class_cache_r_w" ],
    [ "CacheWO", "class_cache_w_o.html", "class_cache_w_o" ],
    [ "Communicator", "class_communicator.html", "class_communicator" ],
    [ "CommunicatorMetrics", "class_communicator_metrics.html", "class_communicator_metrics" ],
    [ "DictOut", "class_dict_out.html", "class_dict_out" ],
    [ "Entry", "class_entry.html", "class_entry" ],
    [ "FPAddr", "union_f_p_addr.html", "union_f_p_addr" ],
    [ "function_traits", "structfunction__traits.html", null ],
    [ "function_traits< ReturnType(ClassType::*)(Args...) const  >", "structfunction__traits_3_01_return_type_07_class_type_1_1_5_08_07_args_8_8_8_08_01const_01_01_4.html", "structfunction__traits_3_01_return_type_07_class_type_1_1_5_08_07_args_8_8_8_08_01const_01_01_4" ],
    [ "Functor", "struct_functor.html", "struct_functor" ],
    [ "GlobalAddress", "class_global_address.html", "class_global_address" ],
    [ "GlobalAllocator", "class_global_allocator.html", "class_global_allocator" ],
    [ "GlobalMemory", "class_global_memory.html", "class_global_memory" ],
    [ "GlobalMemoryChunk", "class_global_memory_chunk.html", "class_global_memory_chunk" ],
    [ "IAMetrics", "class_i_a_metrics.html", null ],
    [ "Incoherent", "struct_incoherent.html", "struct_incoherent" ],
    [ "IncoherentAcquirer", "class_incoherent_acquirer.html", "class_incoherent_acquirer" ],
    [ "IncoherentReleaser", "class_incoherent_releaser.html", "class_incoherent_releaser" ],
    [ "IRMetrics", "class_i_r_metrics.html", null ],
    [ "LocalIterator", "struct_local_iterator.html", "struct_local_iterator" ],
    [ "LRQueue", "class_l_r_queue.html", "class_l_r_queue" ],
    [ "NullAcquirer", "class_null_acquirer.html", "class_null_acquirer" ],
    [ "NullReleaser", "class_null_releaser.html", "class_null_releaser" ],
    [ "PushBuffer", "struct_push_buffer.html", "struct_push_buffer" ],
    [ "range_t", "structrange__t.html", "structrange__t" ],
    [ "remote_task_spawn_args", "structremote__task__spawn__args.html", "structremote__task__spawn__args" ],
    [ "RunningStandardDeviation", "class_running_standard_deviation.html", "class_running_standard_deviation" ],
    [ "SixteenBytes", "struct_sixteen_bytes.html", "struct_sixteen_bytes" ],
    [ "StateTimer", "class_state_timer.html", null ],
    [ "TotalMetric", "class_total_metric.html", "class_total_metric" ]
];