var hierarchy =
[
    [ "Grappa::AdjIterator< V >", "struct_grappa_1_1_adj_iterator.html", null ],
    [ "Aggregator", "class_aggregator.html", null ],
    [ "AggregatorBuffer< max_size_ >", "class_aggregator_buffer.html", null ],
    [ "AggregatorBuffer< buffer_size_ >", "class_aggregator_buffer.html", null ],
    [ "AggregatorGenericCallHeader", "struct_aggregator_generic_call_header.html", null ],
    [ "AggregatorMetrics", "class_aggregator_metrics.html", null ],
    [ "Allocator", "class_allocator.html", null ],
    [ "Allocator< T >", "class_allocator.html", null ],
    [ "AllocatorChunk", "struct_allocator_chunk.html", null ],
    [ "AllReducer< T, ReduceOp >", "class_all_reducer.html", null ],
    [ "function_traits< ReturnType(ClassType::*)(Args...) const  >::arg< i >", "structfunction__traits_3_01_return_type_07_class_type_1_1_5_08_07_args_8_8_8_08_01const_01_01_4_1_1arg.html", null ],
    [ "block_offset_t", "structblock__offset__t.html", null ],
    [ "BufferVector< T >", "class_buffer_vector.html", null ],
    [ "CacheAllocator< T >", "class_cache_allocator.html", null ],
    [ "Cacheline", "struct_cacheline.html", null ],
    [ "CacheMetrics", "class_cache_metrics.html", null ],
    [ "CacheRO< T, Allocator, Acquirer, Releaser >", "class_cache_r_o.html", null ],
    [ "CacheRW< T, Allocator, Acquirer, Releaser >", "class_cache_r_w.html", null ],
    [ "CacheWO< T, Allocator, Acquirer, Releaser >", "class_cache_w_o.html", null ],
    [ "Grappa::GlobalHashMap< K, V >::Cell", "struct_grappa_1_1_global_hash_map_1_1_cell.html", null ],
    [ "Grappa::GlobalHashSet< K >::Cell", "struct_grappa_1_1_global_hash_set_1_1_cell.html", null ],
    [ "Communicator", "class_communicator.html", null ],
    [ "CommunicatorMetrics", "class_communicator_metrics.html", null ],
    [ "Grappa::CompletionEvent", "class_grappa_1_1_completion_event.html", [
      [ "Grappa::GlobalCompletionEvent", "class_grappa_1_1_global_completion_event.html", null ]
    ] ],
    [ "Grappa::ConditionVariable", "class_grappa_1_1_condition_variable.html", null ],
    [ "Grappa::CountingSemaphore", "class_grappa_1_1_counting_semaphore.html", null ],
    [ "DictOut", "class_dict_out.html", null ],
    [ "Grappa::TupleGraph::Edge", "struct_grappa_1_1_tuple_graph_1_1_edge.html", null ],
    [ "Entry", "class_entry.html", null ],
    [ "Grappa::GlobalHashMap< K, V >::Entry", "struct_grappa_1_1_global_hash_map_1_1_entry.html", null ],
    [ "Grappa::GlobalHashSet< K >::Entry", "struct_grappa_1_1_global_hash_set_1_1_entry.html", null ],
    [ "Grappa::File", "struct_grappa_1_1_file.html", null ],
    [ "Grappa::FlatCombiner< T >", "class_grappa_1_1_flat_combiner.html", null ],
    [ "Grappa::FlatCombiner< Grappa::GlobalCounter::Proxy >", "class_grappa_1_1_flat_combiner.html", null ],
    [ "Grappa::FlatCombiner< Grappa::GlobalHashMap::Proxy >", "class_grappa_1_1_flat_combiner.html", null ],
    [ "Grappa::FlatCombiner< Grappa::GlobalHashSet::Proxy >", "class_grappa_1_1_flat_combiner.html", null ],
    [ "Grappa::FlatCombiner< Grappa::GlobalVector::Proxy >", "class_grappa_1_1_flat_combiner.html", null ],
    [ "FPAddr", "union_f_p_addr.html", null ],
    [ "Grappa::FullEmpty< T >", "class_grappa_1_1_full_empty.html", null ],
    [ "Grappa::FullEmpty< R >", "class_grappa_1_1_full_empty.html", null ],
    [ "function_traits< T >", "structfunction__traits.html", null ],
    [ "function_traits< ReturnType(ClassType::*)(Args...) const  >", "structfunction__traits_3_01_return_type_07_class_type_1_1_5_08_07_args_8_8_8_08_01const_01_01_4.html", null ],
    [ "Functor", "struct_functor.html", null ],
    [ "GlobalAddress< T >", "class_global_address.html", null ],
    [ "GlobalAddress< Grappa::GlobalCounter >", "class_global_address.html", null ],
    [ "GlobalAddress< Grappa::GlobalHashMap >", "class_global_address.html", null ],
    [ "GlobalAddress< Grappa::GlobalHashMap::Cell >", "class_global_address.html", null ],
    [ "GlobalAddress< Grappa::GlobalHashSet >", "class_global_address.html", null ],
    [ "GlobalAddress< Grappa::GlobalHashSet::Cell >", "class_global_address.html", null ],
    [ "GlobalAddress< Grappa::GlobalVector >", "class_global_address.html", null ],
    [ "GlobalAddress< Grappa::Graph >", "class_global_address.html", null ],
    [ "GlobalAddress< Grappa::Graph< V > >", "class_global_address.html", null ],
    [ "GlobalAddress< Grappa::TupleGraph::Edge >", "class_global_address.html", null ],
    [ "GlobalAddress< IncoherentAcquirer >", "class_global_address.html", null ],
    [ "GlobalAddress< IncoherentReleaser >", "class_global_address.html", null ],
    [ "GlobalAddress< int64_t >", "class_global_address.html", null ],
    [ "GlobalAddress< V >", "class_global_address.html", null ],
    [ "GlobalAllocator", "class_global_allocator.html", null ],
    [ "Grappa::GlobalCounter", "class_grappa_1_1_global_counter.html", null ],
    [ "Grappa::GlobalHashMap< K, V >", "class_grappa_1_1_global_hash_map.html", null ],
    [ "Grappa::GlobalHashSet< K >", "class_grappa_1_1_global_hash_set.html", null ],
    [ "GlobalMemory", "class_global_memory.html", null ],
    [ "GlobalMemoryChunk", "class_global_memory_chunk.html", null ],
    [ "Grappa::Metrics::GlobalQueueMetrics", "class_grappa_1_1_metrics_1_1_global_queue_metrics.html", null ],
    [ "Grappa::GlobalVector< T, BUFFER_CAPACITY >", "class_grappa_1_1_global_vector.html", null ],
    [ "Grappa::Graph< V >", "struct_grappa_1_1_graph.html", null ],
    [ "IAMetrics", "class_i_a_metrics.html", null ],
    [ "Incoherent< T >", "struct_incoherent.html", null ],
    [ "IncoherentAcquirer< T >", "class_incoherent_acquirer.html", null ],
    [ "IncoherentReleaser< T >", "class_incoherent_releaser.html", null ],
    [ "Grappa::IODescriptor", "struct_grappa_1_1_i_o_descriptor.html", null ],
    [ "IRMetrics", "class_i_r_metrics.html", null ],
    [ "LocalIterator< T >", "struct_local_iterator.html", null ],
    [ "LRQueue", "class_l_r_queue.html", null ],
    [ "Grappa::GlobalCounter::Master", "struct_grappa_1_1_global_counter_1_1_master.html", null ],
    [ "Grappa::GlobalVector< T, BUFFER_CAPACITY >::Master", "struct_grappa_1_1_global_vector_1_1_master.html", null ],
    [ "Grappa::impl::MessageBase", null, [
      [ "Grappa::Message< T >", "class_grappa_1_1_message.html", [
        [ "Grappa::PoolMessage< T >", "class_grappa_1_1_pool_message.html", null ],
        [ "Grappa::ReuseMessage< T >", "class_grappa_1_1_reuse_message.html", null ]
      ] ],
      [ "Grappa::PayloadMessage< T >", "class_grappa_1_1_payload_message.html", [
        [ "Grappa::ExternalCountPayloadMessage< T >", "class_grappa_1_1_external_count_payload_message.html", null ],
        [ "Grappa::PoolPayloadMessage< T >", "class_grappa_1_1_pool_payload_message.html", null ]
      ] ],
      [ "Grappa::Message< DoComplete >", "class_grappa_1_1_message.html", null ]
    ] ],
    [ "Grappa::impl::MetricBase", null, [
      [ "Grappa::CallbackMetric< T >", "class_grappa_1_1_callback_metric.html", null ],
      [ "Grappa::HistogramMetric", "class_grappa_1_1_histogram_metric.html", null ],
      [ "Grappa::MaxMetric< T >", "class_grappa_1_1_max_metric.html", null ],
      [ "Grappa::SummarizingMetric< T >", "class_grappa_1_1_summarizing_metric.html", null ]
    ] ],
    [ "Grappa::Mutex", "class_grappa_1_1_mutex.html", null ],
    [ "NullAcquirer< T >", "class_null_acquirer.html", null ],
    [ "NullReleaser< T >", "class_null_releaser.html", null ],
    [ "Grappa::PiggybackStack< T, Allocator >", "class_grappa_1_1_piggyback_stack.html", null ],
    [ "Grappa::PoolAllocator< Base >", "class_grappa_1_1_pool_allocator.html", [
      [ "Grappa::PoolAllocatorInternal< Bytes, Base >", "class_grappa_1_1_pool_allocator_internal.html", null ]
    ] ],
    [ "Grappa::PoolAllocator< impl::MessageBase >", "class_grappa_1_1_pool_allocator.html", [
      [ "Grappa::impl::MessagePoolBase", null, [
        [ "Grappa::MessagePool", "class_grappa_1_1_message_pool.html", null ],
        [ "Grappa::MessagePoolStatic< Bytes >", "class_grappa_1_1_message_pool_static.html", null ]
      ] ],
      [ "Grappa::SharedMessagePool", "class_grappa_1_1_shared_message_pool.html", null ]
    ] ],
    [ "Grappa::PrefetchingThreadQueue", "class_grappa_1_1_prefetching_thread_queue.html", null ],
    [ "Grappa::delegate::Promise< R >", "class_grappa_1_1delegate_1_1_promise.html", null ],
    [ "Grappa::GlobalCounter::Proxy", "struct_grappa_1_1_global_counter_1_1_proxy.html", null ],
    [ "Grappa::GlobalHashMap< K, V >::Proxy", "struct_grappa_1_1_global_hash_map_1_1_proxy.html", null ],
    [ "Grappa::GlobalHashSet< K >::Proxy", "struct_grappa_1_1_global_hash_set_1_1_proxy.html", null ],
    [ "Grappa::GlobalVector< T, BUFFER_CAPACITY >::Proxy", "struct_grappa_1_1_global_vector_1_1_proxy.html", null ],
    [ "PushBuffer< T, BUFSIZE, NBUFS >", "struct_push_buffer.html", null ],
    [ "Grappa::GlobalVector< T, BUFFER_CAPACITY >::Range", "struct_grappa_1_1_global_vector_1_1_range.html", null ],
    [ "range_t", "structrange__t.html", null ],
    [ "remote_task_spawn_args< A0, A1, A2 >", "structremote__task__spawn__args.html", null ],
    [ "IncoherentAcquirer< T >::RequestArgs", "struct_incoherent_acquirer_1_1_request_args.html", null ],
    [ "IncoherentReleaser< T >::RequestArgs", "struct_incoherent_releaser_1_1_request_args.html", null ],
    [ "Grappa::GlobalHashMap< K, V >::ResultEntry", "struct_grappa_1_1_global_hash_map_1_1_result_entry.html", null ],
    [ "Grappa::GlobalHashSet< K >::ResultEntry", "struct_grappa_1_1_global_hash_set_1_1_result_entry.html", null ],
    [ "Grappa::impl::ReuseList< ReuseMessage< T > >", null, [
      [ "Grappa::ReuseMessageList< T >", "class_grappa_1_1_reuse_message_list.html", null ]
    ] ],
    [ "RunningStandardDeviation", "class_running_standard_deviation.html", null ],
    [ "Grappa::Scheduler", "class_grappa_1_1_scheduler.html", [
      [ "Grappa::BasicScheduler", "class_grappa_1_1_basic_scheduler.html", null ]
    ] ],
    [ "SixteenBytes", "struct_sixteen_bytes.html", null ],
    [ "StateTimer", "class_state_timer.html", null ],
    [ "Grappa::SuspendedDelegateQueue", "class_grappa_1_1_suspended_delegate_queue.html", null ],
    [ "Grappa::ThreadQueue", "class_grappa_1_1_thread_queue.html", null ],
    [ "TotalMetric", "class_total_metric.html", null ],
    [ "Grappa::TupleGraph", "class_grappa_1_1_tuple_graph.html", null ],
    [ "Grappa::VertexBase", "struct_grappa_1_1_vertex_base.html", [
      [ "Grappa::Vertex< T, HeapData >", "struct_grappa_1_1_vertex.html", null ],
      [ "Grappa::Vertex< T, true >", "struct_grappa_1_1_vertex_3_01_t_00_01true_01_4.html", null ]
    ] ],
    [ "Grappa::Worker", "class_grappa_1_1_worker.html", [
      [ "Grappa::SuspendedDelegate", "class_grappa_1_1_suspended_delegate.html", null ]
    ] ]
];